// work in progress not connect with any page



// This snippet file was generated by processing the source file:
// ./auth-next/auth-state-persistence.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_set_persistence_session_modular]
import { getAuth, setPersistence, signInWithEmailAndPassword, browserSessionPersistence } from "https://www.gstatic.com/firebasejs/10.6.0/firebase-auth.js";
import { auth } from './config'
setPersistence(auth, browserSessionPersistence)
    .then(() => {
        // Existing and future Auth states are now persisted in the current
        // session only. Closing the window would clear any existing state even
        // if a user forgets to sign out.
        // ...
        // New sign-in will be persisted with session persistence.
        console.log("wapas jao")
        return signInWithEmailAndPassword(auth, email, password);
    })
    .catch((error) => {
        // Handle Errors here.
        const errorCode = error.code;
        const errorMessage = error.message;
        console.log("wapas jao me masla hai")

    });
// [END auth_set_persistence_session_modular]